/* =========================================================================
   HADES guide — data
   Pure content. No DOM here; consumed by app.js.
   ========================================================================= */

const SECTIONS = [
  { id: 'overview',  label: 'เริ่มต้นที่นี่',   iconPath: 'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20z M15.5 8.5 13 13.5 8.5 15.5 11 10.5z' },
  { id: 'core',      label: 'ระบบหลัก',         iconPath: 'M21 12a9 9 0 1 1-2.64-6.36 M21 4v4h-4' },
  { id: 'mindset',   label: 'Mindset การเล่น',  iconPath: 'M9 18h6 M10 22h4 M12 2a7 7 0 0 0-4 12.7c.6.5 1 1.2 1 2.3h6c0-1.1.4-1.8 1-2.3A7 7 0 0 0 12 2z' },
  { id: 'beginner',  label: 'แผนรันมือใหม่',    iconPath: 'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20z M16 8l-2.5 5.5L8 16l2.5-5.5z' },
  { id: 'chars',     label: 'ตัวละคร',          iconPath: 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M22 21v-2a4 4 0 0 0-3-3.87 M16 3.13a4 4 0 0 1 0 7.75' },
  { id: 'relations', label: 'ผังความสัมพันธ์',   iconPath: 'M8 7a3 3 0 1 0 0-6 3 3 0 0 0 0 6 M4 23v-2a4 4 0 0 1 4-4 M16 7a3 3 0 1 0 0-6 3 3 0 0 0 0 6 M20 23v-2a4 4 0 0 0-4-4 M12 12v4 M8 12h8' },
  { id: 'weapons',   label: 'อาวุธทั้ง 6',      iconPath: 'M14.5 17.5 3 6V3h3l11.5 11.5 M13 19l6-6 M16 16l4 4 M19 21l2-2' },
  { id: 'boons',     label: 'Boon เทพโอลิมปัส', iconPath: 'M13 2 3 14h9l-1 8 10-12h-9z' },
  { id: 'biomes',    label: 'แผนที่ & บอส',     iconPath: 'M9 3 3 6v15l6-3 6 3 6-3V3l-6 3z M9 3v15 M15 6v15' },
  { id: 'upgrades',  label: 'การอัพเกรด',       iconPath: 'M17 11l-5-5-5 5 M17 18l-5-5-5 5' },
  { id: 'keepsakes', label: 'Keepsakes',        iconPath: 'M6 3h12l3 6-9 12L3 9z M3 9h18 M8 9l4-6 4 6 M12 21 8 9 M12 21l4-12' },
];

const OVERVIEW_FEATURES = [
  { label: 'ROGUELIKE',       color: '#ff7a3d', desc: 'ห้อง บอส และรางวัลสุ่มใหม่ทุกครั้ง ไม่มีรันไหนเหมือนกัน' },
  { label: 'ESCAPE',          color: '#e7c26a', desc: 'เป้าหมาย: ทะลุ 4 ด่านจากยมโลกขึ้นสู่พื้นโลก' },
  { label: 'DEATH = PROGRESS', color: '#35cdbd', desc: 'ตายไม่ใช่เกมโอเวอร์ แต่เป็นวงจรของเกมเอง' },
];

const RUN_LOOP = [
  { no: '01', color: '#ff7a3d', title: 'เริ่มรัน',      desc: 'เลือกอาวุธ + keepsake แล้วออกจากบ้าน' },
  { no: '02', color: '#e7c26a', title: 'ผ่านห้อง',      desc: 'เคลียร์ศัตรู เลือกประตู = เลือกรางวัล/boon' },
  { no: '03', color: '#69c46a', title: 'สู้บอส',        desc: 'จบด่านด้วยบอสประจำโซน' },
  { no: '04', color: '#e0453a', title: 'ตาย / สำเร็จ',  desc: 'กลับบ้านผ่านแม่น้ำ Styx เก็บค่าเงินติดตัว' },
  { no: '05', color: '#35cdbd', title: 'อัพเกรด',       desc: 'ใช้ Darkness/Titan Blood อัพถาวร แล้วเริ่มใหม่' },
];

const CURRENCIES = [
  { name: 'Darkness',      use: 'อัพเกรด Mirror of Night (ถาวร)',           color: '#c3b8ff', bg: '#302b52' },
  { name: 'Chthonic Keys', use: 'ปลดล็อกอาวุธใหม่ & ช่องใน Mirror',          color: '#e0cfa0', bg: '#40351f' },
  { name: 'Gemstones',     use: 'จ้าง Contractor ปรับปรุงบ้าน/ปลดฟีเจอร์',   color: '#ff918a', bg: '#48251f' },
  { name: 'Nectar',        use: 'มอบให้ NPC/เทพ → ได้ Keepsake',            color: '#f0cf7a', bg: '#44391d' },
  { name: 'Ambrosia',      use: 'ของขวัญขั้นสูง กระชับสัมพันธ์/เพื่อนร่วมรบ', color: '#f8a5cd', bg: '#482838' },
  { name: 'Titan Blood',   use: 'อัพเกรด Aspect ของอาวุธ',                  color: '#d9a0ed', bg: '#3a234f' },
  { name: 'Diamonds',      use: 'งานปรับปรุงบ้านชิ้นใหญ่',                    color: '#9ce8f4', bg: '#20434b' },
  { name: 'Obols',         use: 'ใช้ในรัน ซื้อของร้าน Charon (หายเมื่อจบรัน)', color: '#f0cf7a', bg: '#44391d' },
];

const MINDSET_TIPS = [
  { no: '01', title: 'ตายคือส่วนหนึ่งของเกม',        body: 'อย่ามองว่าแพ้ ทุกครั้งที่ตายคุณได้ค่าเงินถาวร บทสนทนาใหม่ และเนื้อเรื่องที่เดินหน้า มันคือ "การเล่น" ไม่ใช่ "การจบเกม"' },
  { no: '02', title: 'อย่ารีบเก่ง ค่อย ๆ ปลดล็อก',   body: 'ช่วงแรกโฟกัสอัพ Mirror และปลดอาวุธ ยิ่งอัพเยอะ รันหลัง ๆ ยิ่งไปได้ไกลเอง ไม่ต้องกดดันว่าต้องผ่านไว' },
  { no: '03', title: 'ลองอาวุธให้ครบทุกอัน',         body: 'อย่าติดแค่อันเดียว อาวุธที่มีออร่า Dark Thirst ให้ Darkness เพิ่ม 20% และการลองหลายแบบช่วยให้เจอสไตล์ที่ใช่ของตัวเอง' },
  { no: '04', title: 'วางบิลด์ตาม boon ที่ได้ อย่าฝืน', body: 'ไม่ต้องยึดแผนตายตัว ได้ boon สายไหนแรงก็เดินตามนั้น อ่าน boon ก่อนหยิบเสมอ แล้วโฟกัสไม่กี่เทพ' },
  { no: '05', title: 'กลับบ้านคุยกับทุกคน',          body: 'NPC ในบ้านมีบทใหม่แทบทุกครั้ง เนื้อเรื่องเดิน ได้ของขวัญ และปลดล็อกฟีเจอร์ผ่านบทสนทนา' },
  { no: '06', title: 'อย่าหัวร้อน สนุกกับกระบวนการ',  body: 'เกมนี้ยิ่งเล่นยิ่งเก่งเองตามธรรมชาติ Heat/Pact ค่อยเพิ่มความยากทีหลังเมื่อพร้อม ไม่มีใครกดดันคุณ' },
];

const BEGINNER_RUN_GOALS = [
  { id: 'progress', no: '01', title: 'Progress Run', label: 'ไปให้ไกลที่สุด', color: '#ff7a3d',
    desc: 'ใช้อาวุธที่ถนัด วาง Core Boon ให้เร็ว แล้วแบ่งรางวัลให้ HP และการป้องกันด้วย' },
  { id: 'resource', no: '02', title: 'Resource Run', label: 'เก็บของถาวร', color: '#c98fe0',
    desc: 'ตั้งเป้า Darkness, Key, Nectar หรือ Gemstones เพียงอย่างเดียว แต่ยังต้องมีดาเมจพื้นฐานให้รันไปต่อได้' },
  { id: 'learning', no: '03', title: 'Learning Run', label: 'ทดลองและเรียนรู้', color: '#35cdbd',
    desc: 'ลองอาวุธ Boon หรือ Hammer ใหม่ ผลลัพธ์ของรันนี้คือข้อมูล ไม่ใช่ระยะทาง' },
  { id: 'relationship', no: '04', title: 'Relationship Run', label: 'แจก Nectar', color: '#e7c26a',
    desc: 'พก Nectar ไปให้ตัวละครหรือเทพที่ยังไม่เคยได้ขวดแรก เพื่อเปิด Keepsake เพิ่ม' },
];

const BEGINNER_CHECKLIST = [
  { id: 'weapon', title: 'อาวุธ + ปุ่มหลัก', desc: 'จะทำดาเมจด้วย Attack, Special หรือ Cast เป็นหลัก?' },
  { id: 'keepsake', title: 'Keepsake', desc: 'ต้องการเทพ, HP, ชุบชีวิต หรือเงินเริ่มต้น?' },
  { id: 'build', title: 'ประโยคสรุปบิลด์', desc: 'เช่น “Shield Special ติด Doom” — สั้นแค่หนึ่งประโยคพอ' },
  { id: 'goal', title: 'เป้าหมายของรัน', desc: 'เลือก Progress, Resource, Learning หรือ Relationship หนึ่งอย่าง' },
];

const BEGINNER_DOOR_SCENARIOS = [
  { id: 'no-core', label: 'ยังไม่มี Core Boon', title: 'วางแกนดาเมจก่อน',
    summary: 'ถ้ายังตอบไม่ได้ว่าปุ่มไหนทำดาเมจหลัก ให้เลือก Boon ที่เสริมปุ่มนั้นก่อนรางวัลฟาร์ม แล้วค่อยต่อยอดสิ่งที่ได้จริง',
    priorities: [
      { reward: 'Boon สำหรับปุ่มหลัก', why: 'ทำให้ Attack, Special หรือ Cast ที่กดบ่อยเริ่มเป็นแกนของรัน' },
      { reward: 'Daedalus Hammer', why: 'เปลี่ยนพฤติกรรมอาวุธโดยตรง อ่านทั้งข้อดีและข้อแลกเปลี่ยนก่อนเลือก' },
      { reward: 'Centaur Heart', why: 'เพิ่มพื้นที่ให้ลองผิด โดยเฉพาะเมื่อ Max HP ยังต่ำ' },
      { reward: 'ทรัพยากรถาวร', why: 'เก็บได้เมื่อทางเลือกอื่นไม่แก้จุดอ่อนเร่งด่วนของรัน' },
    ] },
  { id: 'low-hp', label: 'HP / Defiance ต่ำ', title: 'รักษารันที่ยังไปต่อได้',
    summary: 'ดาเมจเพิ่มไม่มีประโยชน์ถ้าไม่มีพื้นที่ให้พลาด เปลี่ยนเป้าหมายชั่วคราวจาก “แรงขึ้น” เป็น “รอดถึงห้องถัดไป”',
    priorities: [
      { reward: 'Centaur Heart / Healing', why: 'เพิ่ม Max HP หรือพา HP กลับสู่ระดับที่ปลอดภัยที่สุดก่อน' },
      { reward: 'ร้าน Charon', why: 'เข้าเมื่อมี Obol พอซื้อของที่ช่วยรอด อย่าเก็บเงินจนจบรัน' },
      { reward: 'Boon ป้องกัน / Dash', why: 'ลดความเสียหายสะสมและช่วยแก้การวางตำแหน่ง' },
      { reward: 'ดาเมจเสริม', why: 'หยิบเมื่อความอยู่รอดนิ่งแล้ว เพื่อไม่ให้การต่อสู้นานเกินไป' },
    ] },
  { id: 'core-ready', label: 'บิลด์เริ่มลงตัว', title: 'ต่อยอดของเดิม ไม่เปิดแกนใหม่',
    summary: 'เมื่อมี Core Boon แล้ว ให้รางวัลทุกชิ้นตอบคำถามว่า “ทำให้ปุ่มหลักดีขึ้นหรือปลอดภัยขึ้นไหม”',
    priorities: [
      { reward: 'Pom ลง Boon หลัก', why: 'เลเวลต้น ๆ มักเห็นผลชัด เลือกอันที่ทำงานแทบทุกห้อง' },
      { reward: 'Boon สนับสนุน', why: 'ต่อสถานะหรือ Synergy ของเดิม แทนการกระจายไปหลายแนว' },
      { reward: 'Hammer ที่เข้าปุ่มหลัก', why: 'เลือกการเปลี่ยนท่าที่สนับสนุนวิธีเล่นปัจจุบัน' },
      { reward: 'HP / ทรัพยากรตามเป้า', why: 'แบ่งช่องให้ความอยู่รอดและเป้าหมายถาวรเมื่อดาเมจเพียงพอ' },
    ] },
  { id: 'resource', label: 'กำลังฟาร์มทรัพยากร', title: 'ฟาร์มโดยไม่ทิ้งความแข็งแรงของรัน',
    summary: 'Resource Run ที่จบเร็วเกินไปมักได้ของน้อยกว่า สร้างบิลด์ขั้นต่ำก่อนแล้วจึงเอนทางเลือกไปยังทรัพยากรเป้าหมาย',
    priorities: [
      { reward: 'Core Boon อย่างน้อย 1 อัน', why: 'ทำให้เคลียร์ห้องได้สม่ำเสมอ แม้รันนี้ไม่ได้ตั้งใจหนีสำเร็จ' },
      { reward: 'ทรัพยากรเป้าหมาย', why: 'เลือก Darkness, Key, Nectar หรือ Gemstones ให้ตรงเป้าหลักของรัน' },
      { reward: 'Heart / Boon ป้องกัน', why: 'ลดโอกาสเสียรันก่อนเก็บของได้คุ้ม' },
      { reward: 'Hammer เมื่อเจอ', why: 'ช่วยให้รันฟาร์มเดินหน้าได้ไกลขึ้นโดยไม่ต้องประกอบบิลด์ซับซ้อน' },
    ] },
];

const BEGINNER_COMBAT_RULES = [
  { no: '01', title: 'อ่าน', body: 'ดู Animation และทิศโจมตีของศัตรูก่อน อย่าเริ่มด้วยการกดรัวทันที' },
  { no: '02', title: 'ตีสั้น', body: 'โจมตีเป็นช่วงสั้น ๆ โดยเฉพาะศัตรูมี Armor ซึ่งไม่ชะงักง่าย' },
  { no: '03', title: 'ย้ายตำแหน่ง', body: 'เก็บ Dash ไว้ตอบท่าสำคัญ แล้วออกจากกับดักหรือมุมที่โดนล้อม' },
];

const BEGINNER_MISTAKES = [
  { problem: 'Dash หมดก่อนท่าสำคัญ', fix: 'หยุดกดแบบ Panic รอดูสัญญาณแล้ว Dash ตามจังหวะ' },
  { problem: 'ยืน Combo จนโดนสวน', fix: 'ตีสั้น ถอย แล้วกลับเข้าเมื่อศัตรูจบท่า' },
  { problem: 'ทุกปุ่มมี Boon แต่ไม่มีปุ่มแรง', fix: 'เลือก Primary Damage หนึ่งปุ่ม แล้วให้รางวัลใหม่ต่อยอดปุ่มนั้น' },
  { problem: 'จบรันพร้อม Obol เหลือเยอะ', fix: 'ใช้เงินก่อนการต่อสู้สำคัญ เพราะ Obol ไม่ติดกลับ House' },
];

const CHARACTER_FILTERS = [
  { id: 'all', label: 'ทั้งหมด' },
  { id: 'family', label: 'ครอบครัวยมโลก' },
  { id: 'underworld', label: 'ชาวยมโลก' },
  { id: 'olympus', label: 'เทพโอลิมปัส' },
  { id: 'allies', label: 'พันธมิตร' },
  { id: 'rivals', label: 'คู่ปรับ' },
];

const CHARACTERS = [
  { id: 'zagreus', name: 'Zagreus', thai: 'ซากรีอัส', latin: 'Prince of the Underworld', faction: 'ราชวงศ์ยมโลก', groups: ['family', 'allies'], role: 'ตัวเอกและเจ้าชายผู้พยายามหนีออกจากยมโลก',
    detail: 'บุตรของ Hades และ Persephone ผู้ไม่ยอมรับชะตาที่ถูกกำหนดไว้ การหลบหนีแต่ละครั้งทำให้เขาค่อย ๆ เปิดเผยความจริงของครอบครัว และช่วยสมานรอยร้าวของผู้คนรอบตัวไปพร้อมกัน',
    relationships: 'Hades กับ Persephone คือพ่อแม่แท้ ๆ, Nyx คือแม่บุญธรรม, Achilles เป็นอาจารย์, Cerberus เป็นสหาย และสามารถสานสัมพันธ์เชิงรักกับ Megaera และ Thanatos ได้',
    encounter: 'เริ่มทุกครั้งที่ห้องนอนใน House of Hades และเป็นตัวละครที่ผู้เล่นควบคุมตลอดเกม',
    unlock: 'ความคืบหน้าของเขาปลดบทสนทนา เนื้อเรื่อง Keepsake และ Companion จากความสัมพันธ์กับตัวละครอื่น' },
  { id: 'hades', name: 'Hades', thai: 'ฮาเดส', latin: 'Lord of the Dead', faction: 'ราชวงศ์ยมโลก', groups: ['family', 'rivals'], role: 'ราชาแห่งยมโลก พ่อของ Zagreus และผู้คุมระเบียบของดวงวิญญาณ',
    detail: 'ผู้ปกครองที่เข้มงวดและพูดจาเย็นชา เขามองการหลบหนีของลูกชายเป็นทั้งการฝ่าฝืนหน้าที่และภัยต่อความลับของครอบครัว ความขัดแย้งของพ่อลูกคือแกนหลักของเรื่อง',
    relationships: 'คู่ครองของ Persephone, บิดาของ Zagreus, พี่น้องของ Zeus และ Poseidon และเป็นนายเหนือเจ้าหน้าที่กับเหล่า Fury ในยมโลก',
    encounter: 'พบประจำหลังโต๊ะทำงานใน House of Hades และเป็นผู้ท้าทายด่านสุดท้ายที่ประตูสู่พื้นโลก',
    unlock: 'เมื่อพัฒนาความสัมพันธ์ถึงช่วงท้ายจะได้รับ Sigil of the Dead และการเรียกพลังของ Hades' },
  { id: 'persephone', name: 'Persephone', thai: 'เพอร์เซโฟนี', latin: 'Queen of the Underworld', faction: 'ราชวงศ์ยมโลก', groups: ['family'], role: 'มารดาของ Zagreus และหัวใจของปริศนาการหลบหนี',
    detail: 'ธิดาของ Demeter ผู้เลือกออกจากยมโลกหลังเหตุการณ์ในอดีต การตามหาเธอบนพื้นโลกเปลี่ยนเป้าหมายของ Zagreus จากการหนีให้กลายเป็นการพาครอบครัวกลับมาเข้าใจกัน',
    relationships: 'คู่ครองของ Hades, มารดาของ Zagreus, ธิดาของ Demeter และเป็นผู้ที่ Nyx กับ Charon ช่วยปกปิดเส้นทางจากเหล่าโอลิมเปียน',
    encounter: 'พบที่สวนบนพื้นโลกหลังผ่าน Hades และภายหลังกลับมาอยู่ใน House of Hades',
    unlock: 'มอบ Pom Blossom ซึ่งเพิ่มระดับ Boon แบบสุ่มเมื่อผ่านห้องตามจำนวนที่กำหนด' },
  { id: 'nyx', name: 'Nyx', thai: 'นิกซ์', latin: 'Night Incarnate', faction: 'ราชวงศ์ยมโลก', groups: ['family', 'underworld'], role: 'เทพีราตรี ผู้บริหารบ้านและแม่บุญธรรมของ Zagreus',
    detail: 'ผู้ทรงอำนาจที่ช่วยชุบชีวิต Zagreus และเลี้ยงดูเขาเมื่อ Persephone จากไป เธอดูแลกลไกเบื้องหลังยมโลกอย่างสุขุม และมีเส้นเรื่องฟื้นความสัมพันธ์กับ Chaos ผู้ให้กำเนิด',
    relationships: 'บุตรของ Chaos, มารดาของ Charon, Thanatos และ Hypnos, แม่บุญธรรมของ Zagreus และผู้บังคับบัญชาของเจ้าหน้าที่ในบ้าน',
    encounter: 'ยืนอยู่ใกล้ทางเข้าห้องของ Hades ใน House of Hades และอาจไปเยือน Chaos ภายหลัง',
    unlock: 'มอบ Mirror of Night ตั้งแต่ต้นเกมและ Black Shawl เมื่อได้รับ Nectar' },
  { id: 'thanatos', name: 'Thanatos', thai: 'ธานาทอส', latin: 'Death Incarnate', faction: 'ครอบครัวแห่งราตรี', groups: ['family', 'allies'], role: 'เทพแห่งความตาย ผู้เก็บวิญญาณและคู่แข่งในสนามรบ',
    detail: 'เพื่อนวัยเด็กของ Zagreus ที่ดูนิ่งและจริงจัง เขาปรากฏในบางห้องเพื่อแข่งขันกำจัดศัตรู ความสัมพันธ์ค่อย ๆ เปิดจากความไม่พอใจที่ Zagreus หนีไปโดยไม่บอกลา',
    relationships: 'บุตรของ Nyx, พี่น้องของ Hypnos และ Charon, เพื่อนร่วมงานของ Megaera และเป็นหนึ่งในความสัมพันธ์เชิงรักที่ Zagreus เลือกได้',
    encounter: 'สุ่มปรากฏในห้องต่อสู้หลังปลดล็อก และกลับมาพบได้ที่ระเบียงฝั่งตะวันตกของ House of Hades',
    unlock: 'มอบ Pierced Butterfly และภายหลังปลด Companion Mort สำหรับสร้างดาเมจมหาศาล' },
  { id: 'hypnos', name: 'Hypnos', thai: 'ฮิปนอส', latin: 'Sleep Incarnate', faction: 'ครอบครัวแห่งราตรี', groups: ['family', 'underworld'], role: 'เทพแห่งการหลับและพนักงานต้อนรับวิญญาณเข้าใหม่',
    detail: 'ตัวละครอารมณ์ดีที่มักทัก Zagreus ด้วยการสรุปสาเหตุการตายอย่างตรงเกินไป เบื้องหลังมุกตลกคือเส้นเรื่องการเรียนรู้ความรับผิดชอบและยืนได้ด้วยตัวเอง',
    relationships: 'บุตรของ Nyx, พี่น้องของ Thanatos และ Charon และเพื่อนร่วมงานที่ถูก Hades ตำหนิเรื่องประสิทธิภาพอยู่เสมอ',
    encounter: 'ยืนข้างแอ่ง Styx ในโถงทางเข้า House of Hades หลังจบแต่ละรัน',
    unlock: 'มอบ Chthonic Coin Purse ซึ่งให้ Obols ทันทีเมื่อสวมใส่' },
  { id: 'charon', name: 'Charon', thai: 'คารอน', latin: 'Ferryman of the Styx', faction: 'ครอบครัวแห่งราตรี', groups: ['family', 'underworld'], role: 'คนแจวเรือแห่ง Styx และพ่อค้าหลักของทุกการหลบหนี',
    detail: 'หนึ่งในบุตรคนโตของ Nyx ผู้พูดเป็นเสียงครางแต่เข้าใจสถานการณ์มากกว่าที่แสดง เขาควบคุมการเดินทางและการค้าของยมโลก และเคยช่วย Persephone อย่างลับ ๆ',
    relationships: 'บุตรของ Nyx, พี่น้องของ Thanatos และ Hypnos, หุ้นส่วนทางการค้าของ Hermes และผู้ร่วมมือเงียบ ๆ ของ Persephone',
    encounter: 'ร้านของ Charon ในแต่ละเขต ห้องก่อนบอส และท่าเรือใน House of Hades',
    unlock: 'มอบ Bone Hourglass; การหยิบถุง Obol ด้านหลังร้านอาจเปิดศึกพิเศษกับเขา' },
  { id: 'cerberus', name: 'Cerberus', thai: 'เซอร์เบอรัส', latin: 'Guardian of the Underworld', faction: 'ราชวงศ์ยมโลก', groups: ['family', 'allies'], role: 'สุนัขสามหัวผู้พิทักษ์บ้านและสหายที่ภักดีที่สุดของ Zagreus',
    detail: 'แม้รูปร่างน่าเกรงขาม Cerberus ชื่นชอบการลูบหัวและของกิน เขาเฝ้าทางออกของ Temple of Styx แต่ยอมหลีกทางเมื่อ Zagreus หา Satyr Sack มาให้',
    relationships: 'สัตว์คู่ใจของ Hades และ Zagreus เป็นที่รักของคนในบ้าน โดยเฉพาะ Megaera กับ Thanatos ที่รู้จักเขามาตั้งแต่วัยเด็ก',
    encounter: 'โถงใหญ่ของ House of Hades และประตูออกจาก Temple of Styx',
    unlock: 'มอบ Old Spiked Collar ซึ่งเพิ่มพลังชีวิตสูงสุด' },
  { id: 'megaera', name: 'Megaera', thai: 'เมกีรา', latin: 'First of the Furies', faction: 'เหล่า Fury', groups: ['underworld', 'rivals', 'allies'], role: 'หัวหน้าพี่น้อง Fury ผู้คุมทางออกจาก Tartarus',
    detail: 'อดีตคนรักและเพื่อนร่วมงานของ Zagreus ผู้ยึดหน้าที่เหนือความรู้สึก เธอต้องหยุดเขาตามคำสั่งของ Hades แต่ยอมรับความซับซ้อนของความสัมพันธ์เมื่อเวลาผ่านไป',
    relationships: 'พี่น้องของ Alecto และ Tisiphone, เพื่อนสนิทของ Dusa, เพื่อนร่วมงานของ Thanatos และเป็นความสัมพันธ์เชิงรักที่ Zagreus เลือกได้',
    encounter: 'บอสท้าย Tartarus และพบดื่มอยู่ในเลานจ์ของ House of Hades หลังการต่อสู้',
    unlock: 'มอบ Skull Earring และปลด Companion Battie เมื่อสายสัมพันธ์สมบูรณ์' },
  { id: 'alecto', name: 'Alecto', thai: 'อเล็กโต', latin: 'The Unceasing', faction: 'เหล่า Fury', groups: ['underworld', 'rivals'], role: 'Fury ผู้หลงใหลการต่อสู้และลงโทษผู้ตกเป็นทาสของอารมณ์',
    detail: 'น้องสาวอารมณ์ร้อนของ Megaera ผู้เรียก Zagreus ว่า Redblood และมองการหยุดเขาเป็นความบันเทิง เธอเน้นความเร็ว การสะสม Rage และพื้นที่อันตรายในสนาม',
    relationships: 'พี่น้องของ Megaera และ Tisiphone รับคำสั่งจาก Hades กับ Nyx และมีหน้าที่ร่วมลงโทษ Sisyphus',
    encounter: 'สุ่มแทน Megaera เป็นบอสท้าย Tartarus หลังเล่นเนื้อเรื่องไปช่วงหนึ่ง และไม่เข้ามาในตัวบ้าน',
    unlock: 'ให้ Nectar หรือ Ambrosia ไม่ได้ แต่การเผชิญหน้าช่วยเปิดบทสนทนา Fury และรูปแบบบอสเพิ่มเติม' },
  { id: 'tisiphone', name: 'Tisiphone', thai: 'ทิซิโฟนี', latin: 'The Avenger', faction: 'เหล่า Fury', groups: ['underworld', 'rivals'], role: 'Fury ผู้หมกมุ่นกับการลงโทษฆาตกร',
    detail: 'พี่น้อง Fury ที่แทบพูดได้เพียงคำว่า “murderer” สนามต่อสู้ของเธอจะค่อย ๆ หดแคบ บังคับให้ผู้เล่นอ่านจังหวะและหลบในพื้นที่จำกัด',
    relationships: 'พี่น้องของ Megaera และ Alecto รับงานจาก Hades และทำหน้าที่ลงทัณฑ์ผู้กระทำผิดร่วมกับเหล่า Fury',
    encounter: 'สุ่มเป็นบอสท้าย Tartarus หลังปลดการหมุนเวียนพี่น้อง Fury',
    unlock: 'ให้ของขวัญไม่ได้ แต่บทสนทนากับ Zagreus ทำให้คำพูดของเธอค่อย ๆ เปลี่ยนไป' },
  { id: 'achilles', name: 'Achilles', thai: 'อคิลลีส', latin: 'Hero of Phthia', faction: 'House of Hades', groups: ['underworld', 'allies'], role: 'ครูฝึก อดีตวีรบุรุษ และผู้เขียนบันทึกใน Codex',
    detail: 'นักรบผู้สุขุมที่ฝึก Zagreus ตั้งแต่ยังเยาว์ เขาแลกสถานะใน Elysium ให้ Patroclus แล้วรับราชการในบ้าน จึงถูกแยกจากคนรักจน Zagreus ช่วยแก้สัญญา',
    relationships: 'คนรักของ Patroclus, อาจารย์และผู้ชี้แนะของ Zagreus และผู้รับใช้ Hades ตามพันธสัญญา',
    encounter: 'ยืนอยู่บริเวณอาวุธและทางเดินฝั่งตะวันตกของ House of Hades',
    unlock: 'มอบ Codex และ Myrmidon Bracer; เส้นเรื่องของเขาปลดการกลับไปพบ Patroclus' },
  { id: 'patroclus', name: 'Patroclus', thai: 'พาโทรคลัส', latin: 'Companion of Achilles', faction: 'Elysium', groups: ['allies'], role: 'นักรบผู้เหนื่อยล้าจากสงครามและคนรักที่พรากจาก Achilles',
    detail: 'อาศัยอยู่โดดเดี่ยวใน Elysium พร้อมความค้างคาใจเรื่องการเสียสละของ Achilles การส่งข้อความระหว่างทั้งคู่เป็นหนึ่งในเส้นเรื่องที่ Zagreus ช่วยคลี่คลาย',
    relationships: 'คนรักของ Achilles และกลายเป็นผู้ช่วยของ Zagreus ผ่านบทสนทนาเกี่ยวกับความทรงจำและการให้อภัย',
    encounter: 'ห้องพักพิเศษใน Elysium ที่ปรากฏแบบสุ่มแทนห้องรางวัลทั่วไป',
    unlock: 'มอบ Broken Spearpoint และเลือกพรชั่วคราว เช่น เติม Death Defiance หรือเพิ่มการป้องกันได้' },
  { id: 'orpheus', name: 'Orpheus', thai: 'ออร์ฟิอัส', latin: 'Court Musician', faction: 'House of Hades', groups: ['underworld', 'allies'], role: 'นักขับลำนำประจำราชสำนัก ผู้สูญเสียแรงบันดาลใจหลังพรากจาก Eurydice',
    detail: 'ศิลปินอ่อนไหวที่ถูก Hades กักไว้เพราะปฏิเสธจะร้องเพลง เส้นเรื่องของเขาเดินผ่านการส่งข่าวถึง Eurydice และการแก้สัญญาเพื่อให้ทั้งคู่กลับมาร้องเพลงร่วมกัน',
    relationships: 'คนรักของ Eurydice, ลูกจ้างของ Hades และเพื่อนนักเล่าเรื่องของ Zagreus',
    encounter: 'ปลดจาก Administrative Chamber ผ่าน House Contractor แล้วพบในเลานจ์ของ House of Hades',
    unlock: 'มอบ Distant Memory และเพิ่มเพลงใน Music Stand ตามความคืบหน้า' },
  { id: 'eurydice', name: 'Eurydice', thai: 'ยูริดิซี', latin: 'Singer of the Underworld', faction: 'Asphodel', groups: ['allies'], role: 'นักร้องและนักทำอาหารผู้เปลี่ยน Boon ให้แข็งแกร่งขึ้น',
    detail: 'วิญญาณผู้มีอารมณ์อบอุ่นแต่ยังเจ็บปวดกับอดีตของ Orpheus เธอใช้ชีวิตเรียบง่ายใน Asphodel และค่อย ๆ เปิดใจเมื่อ Zagreus ช่วยให้ทั้งคู่สื่อสารกันอีกครั้ง',
    relationships: 'คนรักของ Orpheus และมิตรที่เรียก Zagreus อย่างเอ็นดูพร้อมช่วยเตรียมเขาสำหรับทางข้างหน้า',
    encounter: 'ห้องพักพิเศษใน Asphodel สังเกตได้จากเสียงร้องเพลงก่อนเข้าห้อง',
    unlock: 'มอบ Evergreen Acorn และเลือกอัปเกรดความหายากหรือระดับของ Boon ที่มีอยู่' },
  { id: 'sisyphus', name: 'Sisyphus', thai: 'ซิซิฟัส', latin: 'The Ingenious', faction: 'Tartarus', groups: ['allies'], role: 'กษัตริย์ผู้ถูกลงโทษให้เข็นก้อนหินชั่วนิรันดร์',
    detail: 'แม้ถูกลงทัณฑ์ เขายังคงมองโลกในแง่ดีและผูกมิตรกับ Bouldy การช่วยแก้เอกสารโทษของเขาเผยให้เห็นด้านเมตตาของระบบความสัมพันธ์ในเกม',
    relationships: 'สหายของ Bouldy, ผู้ถูก Fury ควบคุมโทษ และเป็นมิตรกับ Zagreus ซึ่งช่วยทบทวนสัญญาของเขา',
    encounter: 'ห้องพักพิเศษใน Tartarus ซึ่งมักไม่มีศัตรู',
    unlock: 'มอบ Shattered Shackle, รางวัล Darkness/Obols/Healing และ Companion Shady เมื่อทำภารกิจสำเร็จ' },
  { id: 'bouldy', name: 'Bouldy', thai: 'โบลดี', latin: 'The Steadfast', faction: 'Tartarus', groups: ['allies'], role: 'ก้อนหินคู่ใจและศูนย์รวมกำลังใจของ Sisyphus',
    detail: 'ก้อนหินที่ Sisyphus ปฏิบัติเหมือนเพื่อนจริง ๆ Zagreus สามารถพูดคุยและมอบ Nectar ให้ได้ เป็นมุกที่กลายเป็นข้อความจริงจังเรื่องการเชื่อในสิ่งที่ช่วยพยุงใจ',
    relationships: 'สหายที่แยกไม่ออกจาก Sisyphus และเป็นเพื่อนเงียบ ๆ ของ Zagreus',
    encounter: 'อยู่ข้าง Sisyphus ในห้องพักพิเศษของ Tartarus',
    unlock: 'รับ Nectar แล้วให้ Boon of Bouldy แบบสุ่มเล็กน้อยหนึ่งอย่างในรันนั้น' },
  { id: 'dusa', name: 'Dusa', thai: 'ดูซา', latin: 'Head Housekeeper', faction: 'House of Hades', groups: ['underworld', 'allies'], role: 'หัวหน้าแม่บ้านกอร์กอนผู้ทุ่มเทกับงานจนเกินพอดี',
    detail: 'ตัวละครขี้อายและพูดเร็วเมื่อเจอ Zagreus ความสัมพันธ์ของทั้งคู่เติบโตเป็นความรักแบบเพื่อนอย่างชัดเจน พร้อมเส้นเรื่องเรื่องคุณค่าของงานและการเคารพขอบเขต',
    relationships: 'เพื่อนสนิทเสมือนพี่น้องของ Megaera, ลูกน้องของ Nyx และเป็นสายสัมพันธ์พิเศษแบบไม่โรแมนติกกับ Zagreus',
    encounter: 'บินทำความสะอาดตามจุดต่าง ๆ ใน House of Hades โดยเฉพาะเลานจ์',
    unlock: 'มอบ Harpy Feather Duster และ Companion Fidi สำหรับเรียกยิงศัตรู' },
  { id: 'skelly', name: 'Skelly', thai: 'สเกลลี', latin: 'The Training Dummy', faction: 'Courtyard', groups: ['underworld', 'allies'], role: 'หุ่นฝึกอมตะที่คอยรับการทดลองอาวุธทุกชนิด',
    detail: 'บุคลิกกวน ๆ ที่สอนกลไกผ่านการยอมให้โจมตี เขาซ่อนที่มาและผู้ว่าจ้างไว้เป็นปริศนา แต่หน้าที่หลักคือให้ผู้เล่นทดสอบคอมโบโดยไม่มีความเสี่ยง',
    relationships: 'ผู้ช่วยฝึกของ Zagreus และมีความเชื่อมโยงลับกับ Charon ซึ่งเป็นผู้จัดหางานให้เขา',
    encounter: 'ลานอาวุธก่อนออกจาก House of Hades',
    unlock: 'มอบ Lucky Tooth, Companion Rib และรางวัลรูปปั้นจากภารกิจ Skelly’s Prizes' },
  { id: 'chaos', name: 'Chaos', thai: 'เคออส', latin: 'The Primordial Originator', faction: 'Primordial', groups: ['family', 'underworld'], role: 'สิ่งมีชีวิตปฐมกาล ผู้ดำรงอยู่ก่อนโลกและเหล่าเทพ',
    detail: 'Chaos มองเหตุการณ์ต่าง ๆ ด้วยความอยากรู้อยากเห็นมากกว่าอารมณ์แบบมนุษย์ พรของพวกเขาแลกบทลงโทษชั่วคราวกับพลังระยะยาว และมีเส้นเรื่องคืนดีกับ Nyx',
    relationships: 'ผู้ให้กำเนิด Nyx และบรรพบุรุษของสายตระกูลแห่งราตรี โดย Zagreus เป็นผู้ช่วยเปิดทางให้ทั้งคู่กลับมาพบกัน',
    encounter: 'ผ่าน Chaos Gate ที่เปิดบนพื้นห้องระหว่างรัน โดยต้องสละพลังชีวิตเพื่อเข้า',
    unlock: 'มอบ Cosmic Egg และ Chaos Boon ที่เริ่มด้วยคำสาปก่อนเปลี่ยนเป็นพลังถาวรของรัน' },
  { id: 'zeus', name: 'Zeus', thai: 'ซุส', latin: 'King of Olympus', faction: 'Olympus', groups: ['olympus', 'family', 'allies'], role: 'ราชาแห่งโอลิมปัสและเทพสายฟ้า',
    detail: 'ผู้นำญาติฝั่งโอลิมปัสที่เข้าใจผิดว่า Zagreus ต้องการขึ้นไปอยู่กับพวกเขา Boon ของ Zeus เน้นสายฟ้าชิ่งและดาเมจเสริมจากการโจมตีหลายครั้ง',
    relationships: 'พี่น้องของ Hades และ Poseidon จึงเป็นลุงฝ่ายพ่อของ Zagreus และเป็นแกนรวมความช่วยเหลือจากโอลิมปัส',
    encounter: 'ห้องรางวัล Boon ของ Zeus และ Trial of the Gods ระหว่างรัน',
    unlock: 'มอบ Thunder Signet เพื่อรับประกันว่า Boon ถัดไปจากเทพจะเป็น Zeus พร้อมเพิ่มความหายาก' },
  { id: 'poseidon', name: 'Poseidon', thai: 'โพไซดอน', latin: 'God of the Sea', faction: 'Olympus', groups: ['olympus', 'family', 'allies'], role: 'เทพสมุทรผู้ร่าเริงและชื่นชอบการแข่งขัน',
    detail: 'ลุงที่ทัก Zagreus อย่างสนิทสนม Boon ของเขาเน้น Knockback, ดาเมจชนกำแพง และรางวัลทรัพยากร เหมาะกับการเคลียร์ห้องอย่างรวดเร็ว',
    relationships: 'พี่น้องของ Hades และ Zeus เป็นลุงฝ่ายพ่อของ Zagreus และมักแข่งขันเชิงมิตรกับน้องชาย',
    encounter: 'ห้องรางวัล Boon ของ Poseidon และ Trial of the Gods',
    unlock: 'มอบ Conch Shell เพื่อชี้เทพองค์ถัดไปให้เป็น Poseidon' },
  { id: 'athena', name: 'Athena', thai: 'อธีนา', latin: 'Goddess of Wisdom', faction: 'Olympus', groups: ['olympus', 'family', 'allies'], role: 'เทพีแห่งปัญญาและการศึก ผู้เปิดการติดต่อจากโอลิมปัส',
    detail: 'เป็นเทพองค์แรกที่ผู้เล่นพบในรันแรก Boon ของเธอใช้ Deflect สะท้อนกระสุนและเพิ่มความปลอดภัย จึงเหมาะกับผู้เล่นใหม่มากที่สุด',
    relationships: 'ญาติรุ่นลูกของราชวงศ์โอลิมปัสและลูกพี่ลูกน้องของ Zagreus ผู้สนับสนุนการหลบหนีอย่างมีเหตุผล',
    encounter: 'Boon เริ่มต้นของรันแรกและห้องรางวัลของ Athena ในรันถัด ๆ ไป',
    unlock: 'มอบ Owl Pendant เพื่อบังคับพบ Athena และเพิ่มโอกาส Boon คุณภาพสูง' },
  { id: 'aphrodite', name: 'Aphrodite', thai: 'อโฟรไดที', latin: 'Goddess of Love', faction: 'Olympus', groups: ['olympus', 'allies'], role: 'เทพีแห่งความรัก ผู้มองเห็นแรงปรารถนาที่ซ่อนอยู่',
    detail: 'Boon ของ Aphrodite ให้ดาเมจพื้นฐานสูงและสถานะ Weak เพื่อลดความเสียหายจากศัตรู บทสนทนาของเธอมักสังเกตความสัมพันธ์ของ Zagreus ได้อย่างตรงจุด',
    relationships: 'พันธมิตรจากโอลิมปัสและผู้แสดงความคิดเห็นต่อสายสัมพันธ์ระหว่าง Zagreus, Megaera และ Thanatos',
    encounter: 'ห้องรางวัล Boon ของ Aphrodite และ Trial of the Gods',
    unlock: 'มอบ Eternal Rose เพื่อรับประกันการพบ Aphrodite ใน Boon ถัดไป' },
  { id: 'ares', name: 'Ares', thai: 'แอรีส', latin: 'God of War', faction: 'Olympus', groups: ['olympus', 'family', 'allies'], role: 'เทพสงครามผู้สนใจจำนวนศัตรูที่ Zagreus สังหาร',
    detail: 'พูดจาสุภาพแต่หลงใหลความรุนแรง Boon ของเขาแบ่งเป็น Doom ที่ระเบิดดาเมจภายหลัง และ Blade Rift ที่สร้างวงใบมีดเคลื่อนที่',
    relationships: 'ญาติฝั่งโอลิมปัสของ Zagreus และชื่นชมงานของ Thanatos ในฐานะความตายที่ตามหลังสงคราม',
    encounter: 'ห้องรางวัล Boon ของ Ares และ Trial of the Gods',
    unlock: 'มอบ Blood-Filled Vial เพื่อชี้ Boon ถัดไปหา Ares' },
  { id: 'artemis', name: 'Artemis', thai: 'อาร์เทมิส', latin: 'Goddess of the Hunt', faction: 'Olympus', groups: ['olympus', 'family', 'allies'], role: 'เทพีแห่งการล่า ผู้รักความสงบและการอยู่ลำพัง',
    detail: 'เป็นญาติที่คุยกับ Zagreus อย่างตรงไปตรงมา Boon ของเธอเพิ่มโอกาส Critical และสร้างดาเมจระเบิดสูง เหมาะกับอาวุธที่โจมตีแรงเป็นจังหวะ',
    relationships: 'ลูกพี่ลูกน้องฝ่ายโอลิมปัสของ Zagreus และมีท่าทีสนิทกับเขามากขึ้นโดยไม่ชอบพิธีรีตองของครอบครัว',
    encounter: 'ห้องรางวัล Boon ของ Artemis และ Trial of the Gods',
    unlock: 'มอบ Adamant Arrowhead เพื่อรับประกัน Boon จาก Artemis' },
  { id: 'dionysus', name: 'Dionysus', thai: 'ไดโอนีซัส', latin: 'God of Wine', faction: 'Olympus', groups: ['olympus', 'family', 'allies'], role: 'เทพแห่งไวน์ งานรื่นเริง และความผ่อนคลาย',
    detail: 'ญาติอารมณ์สบายที่เรียก Zagreus ว่า Zag Boon ของเขาสร้าง Hangover สะสมดาเมจต่อเนื่อง พร้อมความสามารถด้านการฟื้นฟูและเพิ่มพลังชีวิต',
    relationships: 'ญาติฝั่งโอลิมปัสของ Zagreus และร่วมมุกแต่งเรื่องเกี่ยวกับ Orpheus กับต้นกำเนิดของ Zagreus',
    encounter: 'ห้องรางวัล Boon ของ Dionysus และ Trial of the Gods',
    unlock: 'มอบ Overflowing Cup เพื่อชี้ Boon ถัดไปหา Dionysus' },
  { id: 'demeter', name: 'Demeter', thai: 'ดีมีเทอร์', latin: 'Goddess of Seasons', faction: 'Olympus', groups: ['olympus', 'family', 'allies'], role: 'เทพีแห่งฤดูกาลและมารดาของ Persephone',
    detail: 'บุคลิกเย็นชาและโศกเศร้าจากการหายไปของลูกสาว Boon ใช้ Chill ลดความเร็วศัตรูและสร้างความเสียหายจากความหนาว เนื้อเรื่องของเธอเชื่อมตรงกับความลับของ Persephone',
    relationships: 'มารดาของ Persephone จึงเป็นยายฝ่ายแม่ของ Zagreus แม้ช่วงแรกทั้งสองฝ่ายยังไม่รู้ความจริงทั้งหมด',
    encounter: 'เริ่มปรากฏหลังผู้เล่นขึ้นถึงพื้นโลกเป็นครั้งแรก จากนั้นพบในห้อง Boon ตามปกติ',
    unlock: 'มอบ Frostbitten Horn เพื่อรับประกัน Boon จาก Demeter' },
  { id: 'hermes', name: 'Hermes', thai: 'เฮอร์มีส', latin: 'Messenger of the Gods', faction: 'Olympus', groups: ['olympus', 'family', 'allies'], role: 'เทพสารผู้เพิ่มความเร็วและรู้เส้นทางลับของยมโลก',
    detail: 'Hermes พูดเร็วและเข้าใจการหลบหนีมากกว่าที่บอกกับเหล่าโอลิมเปียน Boon ของเขาปรับความเร็ว การ Dash และการฟื้น Cast โดยไม่แย่งช่อง Boon หลัก',
    relationships: 'ญาติฝั่งโอลิมปัสของ Zagreus และหุ้นส่วนทางธุรกิจที่ไว้ใจกันกับ Charon',
    encounter: 'Boon พิเศษตั้งแต่ Asphodel เป็นต้นไป และปรากฏเป็นครั้งคราวในร้านของ Charon',
    unlock: 'มอบ Lambent Plume ซึ่งเพิ่มความเร็วและโอกาสหลบเมื่อเคลียร์ห้องเร็ว' },
  { id: 'theseus', name: 'Theseus', thai: 'ธีซีอัส', latin: 'Hero-King of Athens', faction: 'Elysium', groups: ['rivals'], role: 'แชมเปียนแห่ง Elysium ผู้ชื่นชอบชื่อเสียงและการแสดง',
    detail: 'คู่ปรับเสียงดังที่ตีความ Zagreus เป็นคนร้าย เขาใช้หอกกับโล่และเรียกพลังจากเทพโอลิมปัสเมื่อพลังชีวิตลดลง การต่อสู้ต้องแบ่งความสนใจกับ Asterius',
    relationships: 'สหายร่วมสังเวียนของ Asterius และคู่ปรับที่ยึดติดกับการแข่งขันกับ Zagreus',
    encounter: 'บอสคู่ท้าย Elysium ใน Stadium of Elysium',
    unlock: 'ไม่มี Keepsake แต่ชัยชนะให้รางวัลเขตและเปิดบทสนทนาความขัดแย้งต่อเนื่อง' },
  { id: 'asterius', name: 'Asterius', thai: 'แอสทีเรียส', latin: 'The Minotaur', faction: 'Elysium', groups: ['rivals', 'allies'], role: 'นักรบมิโนทอร์ผู้ทรงเกียรติและคู่หูของ Theseus',
    detail: 'ต่างจาก Theseus เขาเคารพฝีมือของ Zagreus และต่อสู้อย่างตรงไปตรงมา สามารถพบเป็นมินิบอสก่อน เพื่อทำให้พลังชีวิตของเขาในศึกคู่ลดลง',
    relationships: 'สหายที่ซื่อสัตย์ของ Theseus และคู่แข่งซึ่งค่อย ๆ ให้ความเคารพ Zagreus มากขึ้น',
    encounter: 'สุ่มเป็นมินิบอสใน Elysium และปรากฏอีกครั้งในศึกแชมเปียนคู่กับ Theseus',
    unlock: 'ไม่มี Keepsake แต่การพบเดี่ยวเปิดบทสนทนาและช่วยให้ศึกบอสคู่เริ่มด้วยพลังชีวิตน้อยลง' },
  { id: 'house-contractor', name: 'House Contractor', thai: 'ผู้รับเหมาประจำบ้าน', latin: 'Master Renovator', faction: 'House of Hades', groups: ['underworld'], role: 'เจ้าหน้าที่เงียบผู้เปลี่ยนทรัพยากรเป็นการปรับปรุงยมโลก',
    detail: 'โต๊ะทำงานที่มีตัวละครเงาสวมหมวกคอยรับคำสั่งซื้อ งานของเขาครอบคลุมตั้งแต่ของตกแต่ง ไปจนถึงระบบสำคัญอย่าง Fountain Chamber และ Regional Keepsake Collection',
    relationships: 'ทำงานใต้ Hades และรับคำสั่งจาก Zagreus ผ่าน Work Orders เพื่อเปลี่ยนโครงสร้างของบ้านและแต่ละเขต',
    encounter: 'โต๊ะด้านขวาของ Hades ในโถงใหญ่ House of Hades',
    unlock: 'ใช้ Gemstones และ Diamonds เปิดฟีเจอร์ คุณภาพชีวิต เพลง การตกแต่ง และสัญญาที่เกี่ยวกับเส้นเรื่อง' },
  { id: 'wretched-broker', name: 'Wretched Broker', thai: 'นายหน้าวิญญาณ', latin: 'Dealer of Rare Commodities', faction: 'House of Hades', groups: ['underworld'], role: 'พ่อค้าผู้แลกเปลี่ยนทรัพยากรถาวรระหว่างชนิด',
    detail: 'บริการสำคัญสำหรับจัดสมดุลทรัพยากรระยะยาว โดยมีทั้งอัตราแลกปกติและข้อเสนอจำกัดเวลาหลังจบรัน เหมาะกับการเปลี่ยนของส่วนเกินให้เป็นวัตถุดิบที่ขาด',
    relationships: 'เป็นผู้ให้บริการแก่ Zagreus และทำงานอยู่ในระบบเศรษฐกิจของ House of Hades ภายใต้การปกครองของ Hades',
    encounter: 'เลานจ์ของ House of Hades หลังปลดพื้นที่ผ่าน House Contractor',
    unlock: 'เปิดการแลก Darkness, Keys, Nectar, Diamonds, Ambrosia และ Titan Blood ตามอัตราที่กำหนด' },
];

const RELATIONSHIP_TYPES = [
  { id: 'all', label: 'แสดงทั้งหมด' },
  { id: 'blood', label: 'สายเลือด' },
  { id: 'foster', label: 'แม่บุญธรรม' },
  { id: 'romance', label: 'คู่รัก' },
  { id: 'ally', label: 'มิตร / ผู้ชี้แนะ' },
  { id: 'authority', label: 'ผู้บังคับบัญชา' },
  { id: 'rival', label: 'คู่ปรับ' },
];

const CHARACTER_RELATIONSHIPS = [
  { from: 'hades', to: 'persephone', type: 'romance', label: 'คู่ครอง' },
  { from: 'hades', to: 'zagreus', type: 'blood', label: 'พ่อ–ลูก' },
  { from: 'persephone', to: 'zagreus', type: 'blood', label: 'แม่–ลูก' },
  { from: 'demeter', to: 'persephone', type: 'blood', label: 'แม่–ลูก' },
  { from: 'hades', to: 'zeus', type: 'blood', label: 'พี่น้อง' },
  { from: 'hades', to: 'poseidon', type: 'blood', label: 'พี่น้อง' },
  { from: 'zeus', to: 'poseidon', type: 'blood', label: 'พี่น้อง' },
  { from: 'chaos', to: 'nyx', type: 'blood', label: 'ผู้ให้กำเนิด–บุตร' },
  { from: 'nyx', to: 'zagreus', type: 'foster', label: 'แม่บุญธรรม–ลูก' },
  { from: 'nyx', to: 'thanatos', type: 'blood', label: 'แม่–ลูก' },
  { from: 'nyx', to: 'hypnos', type: 'blood', label: 'แม่–ลูก' },
  { from: 'nyx', to: 'charon', type: 'blood', label: 'แม่–ลูก' },
  { from: 'thanatos', to: 'hypnos', type: 'blood', label: 'พี่น้อง' },
  { from: 'megaera', to: 'alecto', type: 'blood', label: 'พี่น้อง Fury' },
  { from: 'megaera', to: 'tisiphone', type: 'blood', label: 'พี่น้อง Fury' },
  { from: 'alecto', to: 'tisiphone', type: 'blood', label: 'พี่น้อง Fury' },
  { from: 'zagreus', to: 'thanatos', type: 'romance', label: 'ความสัมพันธ์ที่เลือกได้' },
  { from: 'zagreus', to: 'megaera', type: 'romance', label: 'อดีตคนรัก / คืนดีได้' },
  { from: 'zagreus', to: 'megaera', type: 'rival', label: 'คู่ต่อสู้ใน Tartarus' },
  { from: 'achilles', to: 'patroclus', type: 'romance', label: 'คนรัก' },
  { from: 'orpheus', to: 'eurydice', type: 'romance', label: 'คนรัก' },
  { from: 'zagreus', to: 'achilles', type: 'ally', label: 'ศิษย์–อาจารย์' },
  { from: 'zagreus', to: 'cerberus', type: 'ally', label: 'สหาย' },
  { from: 'zagreus', to: 'dusa', type: 'ally', label: 'เพื่อนสนิท' },
  { from: 'zagreus', to: 'skelly', type: 'ally', label: 'ผู้ฝึกซ้อม' },
  { from: 'zagreus', to: 'sisyphus', type: 'ally', label: 'มิตร' },
  { from: 'sisyphus', to: 'bouldy', type: 'ally', label: 'สหาย' },
  { from: 'zagreus', to: 'patroclus', type: 'ally', label: 'ผู้ช่วยใน Elysium' },
  { from: 'zagreus', to: 'orpheus', type: 'ally', label: 'ผู้ช่วยคืนสัญญา' },
  { from: 'zagreus', to: 'eurydice', type: 'ally', label: 'ผู้ช่วยระหว่างรัน' },
  { from: 'megaera', to: 'dusa', type: 'ally', label: 'เพื่อนสนิท' },
  { from: 'charon', to: 'hermes', type: 'ally', label: 'หุ้นส่วนทางการค้า' },
  { from: 'zagreus', to: 'zeus', type: 'ally', label: 'ผู้มอบ Boon' },
  { from: 'zagreus', to: 'poseidon', type: 'ally', label: 'ผู้มอบ Boon' },
  { from: 'zagreus', to: 'athena', type: 'ally', label: 'ผู้มอบ Boon' },
  { from: 'zagreus', to: 'aphrodite', type: 'ally', label: 'ผู้มอบ Boon' },
  { from: 'zagreus', to: 'ares', type: 'ally', label: 'ผู้มอบ Boon' },
  { from: 'zagreus', to: 'artemis', type: 'ally', label: 'ผู้มอบ Boon' },
  { from: 'zagreus', to: 'dionysus', type: 'ally', label: 'ผู้มอบ Boon' },
  { from: 'zagreus', to: 'demeter', type: 'ally', label: 'ผู้มอบ Boon' },
  { from: 'zagreus', to: 'hermes', type: 'ally', label: 'ผู้มอบ Boon' },
  { from: 'zagreus', to: 'chaos', type: 'ally', label: 'ผู้มอบพรปฐมกาล' },
  { from: 'hades', to: 'megaera', type: 'authority', label: 'นาย–เจ้าหน้าที่' },
  { from: 'hades', to: 'alecto', type: 'authority', label: 'นาย–เจ้าหน้าที่' },
  { from: 'hades', to: 'tisiphone', type: 'authority', label: 'นาย–เจ้าหน้าที่' },
  { from: 'hades', to: 'achilles', type: 'authority', label: 'นาย–ผู้รับสัญญา' },
  { from: 'hades', to: 'house-contractor', type: 'authority', label: 'ผู้ปกครอง–เจ้าหน้าที่' },
  { from: 'hades', to: 'wretched-broker', type: 'authority', label: 'ผู้ปกครอง–เจ้าหน้าที่' },
  { from: 'nyx', to: 'dusa', type: 'authority', label: 'หัวหน้า–ลูกน้อง' },
  { from: 'alecto', to: 'sisyphus', type: 'authority', label: 'ผู้คุมโทษ–ผู้ถูกลงทัณฑ์' },
  { from: 'zagreus', to: 'alecto', type: 'rival', label: 'คู่ต่อสู้ใน Tartarus' },
  { from: 'zagreus', to: 'tisiphone', type: 'rival', label: 'คู่ต่อสู้ใน Tartarus' },
  { from: 'zagreus', to: 'theseus', type: 'rival', label: 'คู่ปรับใน Elysium' },
  { from: 'zagreus', to: 'asterius', type: 'rival', label: 'คู่แข่งที่เคารพกัน' },
  { from: 'theseus', to: 'asterius', type: 'ally', label: 'คู่หูแชมเปียน' },
  { from: 'zagreus', to: 'house-contractor', type: 'ally', label: 'ผู้ว่าจ้าง–ผู้รับเหมา' },
  { from: 'zagreus', to: 'wretched-broker', type: 'ally', label: 'ผู้ใช้บริการ–พ่อค้า' },
];

const WEAPONS = [
  { id: 'stygius', short: 'Stygius', latin: 'The Stygian Blade', type: 'Sword', diff: 'ง่าย · เหมาะมือใหม่',
    iconPath: 'M14.5 17.5 3 6V3h3l11.5 11.5 M13 19l6-6 M16 16l4 4 M19 21l2-2',
    tagline: 'อาวุธสมดุลรอบด้าน — เกมเริ่มต้นให้ใช้อันนี้ก่อน',
    attack: 'ฟันคอมโบ 3 จังหวะ ระยะประชิด ความเร็วปานกลาง',
    special: 'ฟันหมุนรอบตัว กวาดศัตรูที่รุมประชิดออก',
    playstyle: 'จับง่ายที่สุดในเกม สมดุลทั้งดาเมจ ความเร็ว และระยะ เหมาะใช้เรียนรู้ระบบ boon และหน้าตาของแต่ละด่านก่อนไปลองอาวุธอื่น เป็นอาวุธที่ "ไม่มีจุดอ่อน" แต่ก็ไม่โดดเด่นด้านใดด้านหนึ่ง',
    tips: ['ใช้ dash-strike (dash แล้วกดโจมตี) พุ่งเข้า-ออกไว ๆ ระหว่างคอมโบ', 'special เอาไว้สะบัดเคลียร์ตอนโดนรุมประชิดหลายตัว', 'ตีถี่ = เก็บ boon ที่เสริม "โจมตีปกติ (Attack)" ได้คุ้ม', 'คู่กับ Athena Dash (สะท้อน) แล้วอึดขึ้นมาก'],
    aspects: [
      { name: 'Aspect of Zagreus',  hidden: false, desc: 'เพิ่มความเร็ว Attack และความเร็วเคลื่อนที่ เวอร์ชันตรงไปตรงมาที่สุด', forWho: 'ทุกคน / มือใหม่' },
      { name: 'Aspect of Nemesis',  hidden: false, desc: 'หลังใช้ Special การโจมตี Attack มีโอกาสติดคริติคอลช่วงสั้น ๆ', forWho: 'สายสลับ Special → Attack' },
      { name: 'Aspect of Poseidon', hidden: false, desc: 'เพิ่ม Cast Damage และ Special กระแทก Bloodstone ออกจากศัตรู', forWho: 'สาย Cast / ยิงซ้ำเป็นจังหวะ' },
      { name: 'Aspect of Arthur',   hidden: true,  desc: 'กลายเป็นดาบเอกซ์คาลิเบอร์! ช้าแต่แรงมาก เพิ่ม HP สูงสุด และกางออร่าลดดาเมจที่ได้รับ', forWho: 'สายถึก เปลี่ยนสไตล์ทั้งหมด' },
    ] },
  { id: 'varatha', short: 'Varatha', latin: 'The Eternal Spear', type: 'Spear', diff: 'ง่าย-กลาง',
    iconPath: 'M4 20 20 4 M14 4h6v6 M9 15l-4 4',
    tagline: 'ระยะเอื้อมไกล + หมุนกวาดเป็นวงกว้าง',
    attack: 'แทงระยะไกลกว่าดาบ ตีโดนก่อนโดนตี ปลอดภัยกว่า',
    special: 'ขว้างหอกเป็นเส้นตรง แล้วกดซ้ำเพื่อเรียกกลับและทำดาเมจขากลับ',
    playstyle: 'ได้เปรียบเรื่องระยะเป็นหลัก เก็บศัตรูจากไกลได้ปลอดภัย จุดเด่นคือ Spin Attack (กดค้าง) ที่กวาดเป็นวงรอบตัว เคลียร์ฝูงและกันตัวได้ดีมาก เป็นอาวุธอเนกประสงค์ที่หลายคนชอบ',
    tips: ['กด Attack ค้างเพื่อชาร์จ Spin กวาดวงกว้าง แล้วปล่อยเมื่อมีช่อง', 'ใช้ระยะแทงเช็กและกดดันบอสได้ปลอดภัย', 'ขว้างหอกใส่ศัตรูไกล แล้วกด Special ซ้ำให้ดาเมจขากลับโดนอีกครั้ง', 'เลือกว่าจะเน้น Attack, Special หรือ Spin ให้ชัดก่อนหยิบ boon'],
    aspects: [
      { name: 'Aspect of Zagreus',  hidden: false, desc: 'เพิ่มดาเมจ ระยะ และความเร็วของ Special เหมาะกับการขว้างจากระยะปลอดภัย', forWho: 'ทุกคน / มือใหม่' },
      { name: 'Aspect of Achilles', hidden: false, desc: 'หลัง Special ใช้ Raging Rush พุ่งตามหอก และบัฟ Attack/Cast ชั่วคราว', forWho: 'สายคอมโบขว้าง-พุ่ง / Cast' },
      { name: 'Aspect of Hades',    hidden: false, desc: 'Spin กลายเป็น Punishing Sweep ทำให้ศัตรูรับดาเมจจาก Attack/Special เพิ่มช่วงหนึ่ง', forWho: 'สาย Spin เปิดเป้าแล้วตามโจมตี' },
      { name: 'Aspect of Guan Yu',  hidden: true,  desc: 'ลด HP สูงสุดลงมาก แลกดาเมจกวาดมหาศาล + ดูดเลือดคืน', forWho: 'โปรสายเสี่ยง เก่งแล้ว' },
    ] },
  { id: 'aegis', short: 'Aegis', latin: 'The Shield of Chaos', type: 'Shield', diff: 'ง่าย · อึดสุด',
    iconPath: 'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z',
    tagline: 'บล็อกได้ ขว้างเด้ง — เหมาะมือใหม่ที่สุด',
    attack: 'ตีระยะประชิด ช้าแต่หนัก และกดค้างเพื่อบล็อก',
    special: 'ขว้างโล่พุ่งไปเด้งกลับ โดนหลายตัว / กดค้าง = Bull Rush พุ่งชน',
    playstyle: 'อาวุธที่ทนที่สุด กดค้างเพื่อบล็อกกันดาเมจได้เกือบทุกอย่างจากด้านหน้า แล้วปล่อยจังหวะพอดีเพื่อ Bull Rush สวนกลับ เหมาะกับคนที่กลัวตายหรือยังหลบไม่คล่อง',
    tips: ['กดค้างบล็อกจังหวะบอสยิงรัว ๆ กันได้เกือบหมด', 'ปล่อยบล็อกจังหวะพอดี = Bull Rush พุ่งสวน', 'ขว้างโล่เด้งไปมาเก็บศัตรูหลายตัว', 'boon ใส่ special (โล่ขว้าง) คุ้มมาก'],
    aspects: [
      { name: 'Aspect of Zagreus', hidden: false, desc: 'Bull Rush โดนแรงขึ้น / ปล่อยได้หลายลูก', forWho: 'ทุกคน / มือใหม่' },
      { name: 'Aspect of Chaos',   hidden: false, desc: 'โล่ที่ขว้างเด้งได้หลายครั้งขึ้น เก็บทั้งห้อง', forWho: 'สายขว้างเด้งเก็บฝูง' },
      { name: 'Aspect of Zeus',    hidden: false, desc: 'โล่ขว้างกลายเป็นโล่สายฟ้าช็อตต่อเนื่อง แข็งและ AoE โหด', forWho: 'สายไฟฟ้า (แนะนำมาก)' },
      { name: 'Aspect of Beowulf', hidden: true,  desc: 'โล่หนักพิเศษ กลไก Bull Rush ผูกกับ cast เล่นสาย cast จัดเต็ม', forWho: 'สาย cast เฉพาะทาง' },
    ] },
  { id: 'coronacht', short: 'Coronacht', latin: 'The Heart-Seeking Bow', type: 'Bow', diff: 'กลาง',
    iconPath: 'M17 3a12 12 0 0 1 0 18 M17 3 4 12l13 9 M4 12h9',
    tagline: 'ราชาระยะไกล เบิร์สต์ดาเมจสูง',
    attack: 'ชาร์จยิง (Power Shot) ยิ่งชาร์จเต็มยิ่งแรง',
    special: 'ยิงลูกธนูกระจาย (Volley) ผลักศัตรูถอยห่าง',
    playstyle: 'จัดการศัตรูจากไกลก่อนเข้าถึงตัว ต้องขยับหนีเก่งและเล็งแม่น จุดแข็งคือเบิร์สต์บอสได้ไวมากด้วย Power Shot เต็มแรง เหมาะคนชอบเล่นปลอดภัยแบบยืนไกล',
    tips: ['ชาร์จเต็มก่อนปล่อยเสมอเพื่อ Power Shot ดาเมจสูง', 'special ผลักศัตรูที่เข้าประชิดให้ห่างแล้วค่อยยิงต่อ', 'ขยับตลอด อย่ายืนนิ่ง เพราะเลือดน้อยกว่าสายประชิด', 'boon เสริมคริ (Artemis) หรือ Power Shot คุ้มสุด'],
    aspects: [
      { name: 'Aspect of Zagreus', hidden: false, desc: 'Power Shot แรงขึ้น สมดุล', forWho: 'ทุกคน / มือใหม่' },
      { name: 'Aspect of Chiron',  hidden: false, desc: 'special ตามล็อกศัตรูตัวที่โจมตีล่าสุด (โฮมมิ่ง)', forWho: 'สายยิงตามเป้า (แนะนำ)' },
      { name: 'Aspect of Hera',    hidden: false, desc: 'โจมตีปกติ "บรรจุ" cast ลงธนู ยิง cast ออกไปได้', forWho: 'สาย cast / bloodstone โหด' },
      { name: 'Aspect of Rama',    hidden: true,  desc: 'special ปักหมายศัตรู แล้วโจมตีชาร์จใส่เป้าที่ปักแรงพิเศษ', forWho: 'สายบอส / เป้าเดี่ยว' },
    ] },
  { id: 'malphon', short: 'Malphon', latin: 'The Twin Fists', type: 'Fists', diff: 'กลาง-ยาก',
    iconPath: 'M6 12V8a2 2 0 0 1 4 0 M10 8V6a2 2 0 0 1 4 0v2 M14 8a2 2 0 0 1 4 0v5a6 6 0 0 1-6 6H9a5 5 0 0 1-5-5v-1a2 2 0 0 1 2-2z',
    tagline: 'เร็ว ดุ DPS ประชิดสูงสุดในเกม',
    attack: 'ต่อยรัวเร็วมาก ระยะสั้น',
    special: 'พุ่งอัปเปอร์คัต (dash-uppercut) เข้าหาศัตรู',
    playstyle: 'สายบุกดุดันที่สุด เข้าประชิดหน้าตลอด ต้องหลบเก่งเพราะระยะสั้นทำให้เสี่ยงโดนตี แต่ถ้าเล่นเป็น DPS ถล่มทลาย เหมาะคนชอบเล่นเชิงรุกและมั่นใจการหลบ',
    tips: ['ต่อยรัวสลับ dash หลบ เข้า-ออกตลอดเวลา', 'special พุ่งเข้าหา = ทั้งเข้าถึงตัวและหลบไปในตัว', 'ระยะสั้น = เสี่ยง เล่นคู่ Athena/Aphrodite เพื่ออยู่รอด', 'boon เสริม attack (ต่อย) คุ้มสุดเพราะตีถี่ที่สุด'],
    aspects: [
      { name: 'Aspect of Zagreus',   hidden: false, desc: 'เพิ่มจำนวน dash-uppercut', forWho: 'ทุกคน / มือใหม่' },
      { name: 'Aspect of Talos',     hidden: false, desc: 'โจมตี/special ดูดศัตรูเข้าหา (แม่เหล็ก) + ดาเมจโบนัสกับตัวที่ถูกดูด', forWho: 'สายรวมศัตรูเป็นกอง' },
      { name: 'Aspect of Demeter',   hidden: false, desc: 'special กลายเป็นคลื่นระยะไกลผลักแรง (Rush)', forWho: 'สายเพิ่มระยะ + knockback' },
      { name: 'Aspect of Gilgamesh', hidden: true,  desc: 'เปลี่ยน dash-strike เป็นท่าเชือด + special ติดสถานะ นักสู้สายเทคนิค', forWho: 'โปรสายบุก' },
    ] },
  { id: 'exagryph', short: 'Exagryph', latin: 'The Adamant Rail', type: 'Rail', diff: 'กลาง',
    iconPath: 'M12 2v4 M12 18v4 M2 12h4 M18 12h4 M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20z M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z',
    tagline: 'ยิงรัวระยะไกล + ระเบิด AoE',
    attack: 'ยิงกระสุนรัวอัตโนมัติ มีระบบรีโหลด',
    special: 'ยิงระเบิด (Bombard) ลง AoE',
    playstyle: 'สเปรย์กระสุนใส่ + ระเบิดเคลียร์ฝูง จัดการศัตรูหลายตัวพร้อมกันได้ดี จุดต้องระวังคือจังหวะรีโหลด อย่ายิงจนหมดกลางดงศัตรู เหมาะคนชอบเล่นยิงกระจายแบบ kite',
    tips: ['อย่ายิงจนกระสุนหมดกลางดง — รีโหลดตอนปลอดภัย', 'special ระเบิดเคลียร์ศัตรูที่รวมกลุ่มกัน', 'ขยับยิง (kite) ไม่ให้ศัตรูประชิด', 'boon ที่ติดทุกนัด (Zeus/Aphrodite) คุ้มเพราะยิงรัว'],
    aspects: [
      { name: 'Aspect of Zagreus', hidden: false, desc: 'แม็กกาซีนใหญ่ขึ้น ยิงได้นานขึ้นก่อนรีโหลด', forWho: 'ทุกคน / มือใหม่' },
      { name: 'Aspect of Eris',    hidden: false, desc: 'หลังยิง Bombard ได้บัฟดาเมจ (แลกกับเสี่ยงโดนระเบิดตัวเอง)', forWho: 'สายดาเมจดุดัน' },
      { name: 'Aspect of Hestia',  hidden: false, desc: 'รีโหลดแบบ active (จังหวะพอดี) ทำให้นัดถัดไปแรง + bombard ติดเป้า', forWho: 'สายรีโหลดจับจังหวะ' },
      { name: 'Aspect of Lucifer', hidden: true,  desc: 'special กลายเป็นลำแสงเผาต่อเนื่อง มีระบบความร้อน (overheat)', forWho: 'สายลำแสงต่อเนื่อง' },
    ] },
];

const BUILDS = {
  stygius: [
    { name: 'Chain Lightning Blade', tag: 'ชุมชนแนะนำ · มือใหม่', core: 'Aspect of Zagreus/Nemesis + Zeus (Attack) + Athena (Dash)', why: 'ตีปกติแถมฟ้าผ่าเด้งทั้งจอ ส่วน Athena Dash กันตายให้ยืนตีสบาย เข้าใจง่ายและแรงตั้งแต่รันแรก ๆ' },
    { name: 'Nemesis Crit', tag: 'เบิร์สต์สูง', core: 'Aspect of Nemesis + Artemis (Attack) + Aphrodite (Special)', why: 'จบคอมโบแล้วครั้งถัดไปคริการันตี รวมกับคริของ Artemis = ฟันเดียวหายครึ่งหลอด' },
    { name: 'Tanky Arthur', tag: 'เปลี่ยนสไตล์ · สายอึด', core: 'Aspect of Arthur + Athena/Aphrodite + Chthonic Vitality', why: 'ดาบเอกซ์คาลิเบอร์ช้าแต่แรง กางออร่าลดดาเมจ + เลือดเยอะ เดินฝ่าแทบทุกอย่างได้' },
  ],
  varatha: [
    { name: 'Hades Spin', tag: 'ชุมชนแนะนำ', core: 'Aspect of Hades + Demeter/Ares (Special) + Athena (Dash)', why: 'ชาร์จ Punishing Sweep หมุนกวาดดาเมจมหาศาลรอบตัว ติดสถานะทั้งวง เคลียร์ห้องแทบวินาทีเดียว' },
    { name: 'Achilles Rush', tag: 'สายคอมโบมันส์', core: 'Aspect of Achilles + Ares/Artemis (Special) + Hermes', why: 'ขว้างหอกแล้ว dash-strike ครั้งถัดไปแรงพิเศษ วนพุ่งเข้า-ออกไม่หยุด สนุกมือ' },
    { name: 'Guan Yu Lifesteal', tag: 'โปร · เสี่ยงสูง', core: 'Aspect of Guan Yu + Aphrodite + Life boon', why: 'เลือดน้อยแต่กวาดแรงและดูดเลือดคืน เล่นเป็นแล้วโหดสุด สายชอบความท้าทาย' },
  ],
  aegis: [
    { name: 'Lightning Shield', tag: 'ชุมชนแนะนำ · แนะนำมาก', core: 'Aspect of Zeus + Zeus (Special) + Athena (Dash)', why: 'ขว้างโล่กลายเป็นสายฟ้าช็อตต่อเนื่อง AoE โหด บล็อกกันตายได้ด้วย อึดและแรงพร้อมกัน' },
    { name: 'Chaos Bounce', tag: 'เก็บฝูงเพลิน', core: 'Aspect of Chaos + Ares/Aphrodite (Special) + Poseidon', why: 'โล่ขว้างเด้งไปมาหลายครั้งเก็บทั้งห้อง ยิ่งเด้งยิ่งติดสถานะกระจาย' },
    { name: 'Beowulf Caster', tag: 'สาย Cast เฉพาะทาง', core: 'Aspect of Beowulf + Ares (Blade Rift) / Demeter (Cast) + Bloodstones', why: 'ผูกกลไกกับ cast ปักใบมีด/หินเลือดใส่ศัตรูรัว ๆ บิลด์คิดเยอะแต่ทรงพลัง' },
  ],
  coronacht: [
    { name: 'Chiron Homing', tag: 'ชุมชนแนะนำ · แนะนำมาก', core: 'Aspect of Chiron + Artemis (Special) + Zeus/Aphrodite (Attack)', why: 'special ล็อกตามศัตรูอัตโนมัติ ยิงรัวคริไม่ต้องเล็ง เบิร์สต์บอสร่วงไวมาก' },
    { name: 'Hera Cannon', tag: 'สาย Cast ระเบิด', core: 'Aspect of Hera + Ares/Aphrodite (Cast) + Bloodstones', why: 'โจมตีปกติบรรจุ cast ลงธนูแล้วยิงออก = ยิง bloodstone ทะลุจอ ดาเมจก้อนโต' },
    { name: 'Power Shot Sniper', tag: 'สายยิงไกลปลอดภัย', core: 'Aspect of Rama/Zagreus + Artemis (Attack) + Hermes', why: 'ชาร์จเต็มยิงทีละนัดหนัก ๆ ยืนไกลเก็บทีละตัว ปลอดภัยสายเล่นใจเย็น' },
  ],
  malphon: [
    { name: 'Talos Magnet', tag: 'ชุมชนแนะนำ', core: 'Aspect of Talos + Zeus/Poseidon (Attack) + Athena (Dash)', why: 'ดูดศัตรูมากองรวมกันแล้วต่อยรัว AoE ติดทุกตัว สะใจและเคลียร์ฝูงไว' },
    { name: 'Demeter Frost', tag: 'คุมเกม + ระยะ', core: 'Aspect of Demeter + Aphrodite/Athena + Chill boon', why: 'special กลายเป็นคลื่นระยะไกลผลัก + Chill ชะลอศัตรู แก้จุดอ่อนระยะสั้นของหมัด' },
    { name: 'Lightning Fists', tag: 'สายบุกดุ', core: 'Aspect of Zagreus + Hermes + Ares/Zeus (Attack)', why: 'ต่อยเร็วอยู่แล้ว + Hermes เร่งความไว = DPS ประชิดสูงสุดในเกม เข้า-ออกไวจนศัตรูตามไม่ทัน' },
  ],
  exagryph: [
    { name: 'Hestia Sniper', tag: 'ชุมชนแนะนำ', core: 'Aspect of Hestia + Artemis (Attack) + Zeus', why: 'รีโหลดจับจังหวะพอดี = นัดถัดไปแรงพิเศษ + คริ ยิงทีละนัดเจ็บ ๆ เหมือนสไนเปอร์' },
    { name: 'Bombard Spam', tag: 'เคลียร์ฝูงเพลิน', core: 'Aspect of Eris/Zagreus + Ares/Zeus (Bombard) + Poseidon', why: 'อัด boon ลงระเบิด (Bombard) แล้วสาดใส่กองศัตรู ระเบิดต่อเนื่องทั้งจอ' },
    { name: 'Lucifer Beam', tag: 'เปลี่ยนสไตล์', core: 'Aspect of Lucifer + Aphrodite/Demeter (Special) + Life', why: 'special เป็นลำแสงเผาต่อเนื่อง กวาดค้างใส่บอส คุมความร้อน (overheat) ให้ดีคือแรงมาก' },
  ],
};

const GODS = [
  { id: 'zeus', name: 'Zeus', latin: 'God of the Sky', color: '#f5d33f', statusBg: '#443b1b', domain: 'สายฟ้า', status: 'Jolted — ฟ้าผ่าซ้ำ',
    signature: ['ฟ้าผ่าลูกโซ่เด้งไปหลายตัว', 'โจมตี/special แถมสายฟ้า AoE กระจาย'],
    synergy: 'ราชาแห่งการเคลียร์ฝูงด้วย AoE คู่กับ Poseidon หรือ Demeter ได้ duo แรงมาก มือใหม่หยิบง่ายเพราะดาเมจมาเอง' },
  { id: 'poseidon', name: 'Poseidon', latin: 'God of the Sea', color: '#67bdff', statusBg: '#1b3a52', domain: 'คลื่นทะเล', status: 'Knockback — กระแทก',
    signature: ['ผลักศัตรูกระแทกกำแพง/กับดัก = ดาเมจเพิ่ม', 'ทำให้ดรอปเงินและรางวัลมากขึ้น'],
    synergy: 'ผลักศัตรูลงลาวา/หนามได้เปรียบสุด ๆ ใน Asphodel แถมช่วยเก็บเงินเยอะ' },
  { id: 'athena', name: 'Athena', latin: 'Goddess of Wisdom', color: '#9ce2d2', statusBg: '#20483f', domain: 'ป้องกัน', status: 'Deflect — สะท้อน',
    signature: ['Divine Dash — dash สะท้อนกระสุนและดาเมจ', 'ทำ Exposed ลดเกราะศัตรู'],
    synergy: 'แกนหลักสายเอาตัวรอด ถ้าเจอ Athena Dash ให้รีบหยิบ เป็น boon ท็อปที่เข้าได้กับทุกบิลด์' },
  { id: 'aphrodite', name: 'Aphrodite', latin: 'Goddess of Love', color: '#ff99bf', statusBg: '#492739', domain: 'เสน่หา', status: 'Weak — ศัตรูอ่อนแรง',
    signature: ['ทำ Weak ให้ศัตรูตีเบาลง', 'Charm ทำให้ศัตรูหันไปตีกันเอง'],
    synergy: 'เพิ่มทั้งดาเมจและความอยู่รอดในตัวเดียว มือใหม่หยิบไปไม่มีทางพลาด' },
  { id: 'ares', name: 'Ares', latin: 'God of War', color: '#ff7c70', statusBg: '#49231e', domain: 'สงคราม', status: 'Doom — ระเบิดหน่วงเวลา',
    signature: ['Doom สะสมดาเมจแล้วระเบิดออกทีเดียว', 'Blade Rift — cast ใบมีดหมุนติดพื้น'],
    synergy: 'ดาเมจดิบสูง คู่กับ Artemis (คริ) หรือ Aphrodite (Weak) ได้ duo โหด ๆ' },
  { id: 'artemis', name: 'Artemis', latin: 'Goddess of the Hunt', color: '#8adb8b', statusBg: '#254728', domain: 'ล่าสัตว์', status: 'Critical — คริติคอล',
    signature: ['เพิ่มโอกาสคริทุกการโจมตี', 'ลูกธนู/กระสุนตามล็อกเป้า'],
    synergy: 'จับคู่กับดาเมจเป้าเดียวหรือธนู เบิร์สต์บอสร่วงไว มาเป็น boon เดี่ยว ๆ ก็แรง' },
  { id: 'dionysus', name: 'Dionysus', latin: 'God of Wine', color: '#c49aee', statusBg: '#38254c', domain: 'สุราเมรัย', status: 'Hangover — พิษสะสม',
    signature: ['ติดพิษ Hangover ค่อย ๆ กัดเลือดต่อเนื่อง', 'Festive Fog — หมอกพิษ AoE ยืนกดดาเมจ'],
    synergy: 'ดาเมจต่อเนื่องแบบ "ติดแล้วหนี" ยืนระยะสบาย เหมาะมือใหม่ที่ยังหลบไม่คล่อง' },
  { id: 'demeter', name: 'Demeter', latin: 'Goddess of Seasons', color: '#d0edf2', statusBg: '#26434a', domain: 'น้ำแข็ง/เก็บเกี่ยว', status: 'Chill — ชะลอ→แช่แข็ง',
    signature: ['Chill ทำศัตรูช้าลง สะสมเต็มเป็น Deep Freeze', 'ดาเมจสูงพร้อมคุมฝูงในตัว'],
    synergy: 'คุมเกม + ดาเมจครบเครื่อง คู่ Zeus/Poseidon ได้ duo เด่นมาก' },
  { id: 'hermes', name: 'Hermes', latin: 'The Messenger', color: '#ffc36c', statusBg: '#49351c', domain: 'ความเร็ว', status: 'Speed — ว่องไว',
    signature: ['เพิ่มความเร็ววิ่ง/โจมตี/dash', 'เพิ่มจำนวน dash และโอกาสหลบ'],
    synergy: 'มักโผล่กลางรัน (ไม่ผ่านประตูปกติ) เจอเมื่อไหร่เก็บเสริมความไว = เอาตัวรอดดีขึ้นทันตา' },
  { id: 'chaos', name: 'Chaos', latin: 'The Primordial', color: '#c0a4f2', statusBg: '#38284f', domain: 'ความอลหม่าน', status: 'คำสาป → บัฟถาวร',
    signature: ['ผ่านประตู Chaos รับคำสาปสั้น ๆ แลกพลังถาวรทั้งรัน', 'บัฟมักแรงกว่า boon เทพปกติ'],
    synergy: 'ทนคำสาปช่วงสั้น ๆ เพื่อของดีระยะยาว คุ้มถ้าเลือดยังเยอะและด่านยังอีกไกล' },
];

const STATUSES = [
  { name: 'Jolted', god: 'Zeus', color: '#f5d33f', how: 'ติดแล้ว เมื่อศัตรู "โจมตี" จะโดนฟ้าผ่าใส่ตัวเอง', detail: 'ดีกับบอสหรือศัตรูที่ตีถี่ ยิ่งมันดุยิ่งเจ็บตัวเอง เป็นดาเมจฟรีที่ไม่ต้องทำอะไรเพิ่ม' },
  { name: 'Weak', god: 'Aphrodite', color: '#ff7fb0', how: 'ลดดาเมจที่ศัตรูสร้าง ~30% ชั่วคราว', detail: 'เป็นเกราะชั้นดี ใส่ก่อนบอสปล่อยท่าหนักทำให้ตีเราเบาลงมาก อยู่รอดง่ายขึ้นทันตา' },
  { name: 'Doom', god: 'Ares', color: '#e0453a', how: 'ปักไว้แล้วระเบิดดาเมจก้อนใหญ่หลังหน่วงเวลาสั้น ๆ', detail: 'ดาเมจดิบสูงสุดสายหนึ่ง แต่ยิงซ้ำก่อนระเบิดจะรีเซ็ตเวลา — ปล่อยให้ระเบิดก่อนค่อยตีซ้ำ' },
  { name: 'Hangover', god: 'Dionysus', color: '#9b6fce', how: 'พิษสะสมกัดเลือดต่อเนื่อง ซ้อนได้หลายชั้น', detail: 'ยิ่งตีโดนยิ่งซ้อนชั้น เหมาะสไตล์ "ติดแล้วหนี" ปล่อยพิษทำงานเอง มือใหม่ที่ยังหลบไม่คล่องชอบมาก' },
  { name: 'Chill → Deep Freeze', god: 'Demeter', color: '#bfe3ea', how: 'ชะลอความเร็วศัตรู สะสมเต็มเป็น Deep Freeze แช่แข็งชั่วขณะ', detail: 'คุมฝูงชั้นเยี่ยม ศัตรูช้าลง = หลบง่าย ตีง่าย พร้อมดาเมจในตัว คุ้มทั้งรุกและรับ' },
  { name: 'Marked / Critical', god: 'Artemis', color: '#69c46a', how: 'เพิ่มโอกาสคริ (ดาเมจเด้ง) บางพรทำเครื่องหมายเป้า', detail: 'สเกลกับดาเมจต่อครั้งได้ดี รวมกับอาวุธตีแรงหรือ Power Shot = เบิร์สต์บอสร่วงไว' },
  { name: 'Deflect / Exposed', god: 'Athena', color: '#87d3c2', how: 'Deflect สะท้อนกระสุน/ดาเมจกลับ · Exposed เพิ่มดาเมจตอนตีข้างหลัง', detail: 'Athena Dash คือ boon เอาตัวรอดอันดับต้น ๆ ของเกม เจอเมื่อไหร่รีบหยิบ เข้าได้กับทุกบิลด์' },
  { name: 'Knockback', god: 'Poseidon', color: '#3aa0e8', how: 'กระแทกศัตรูกระเด็น ชนกำแพง/กับดัก/ลาวา = ดาเมจเพิ่ม', detail: 'คุมพื้นที่ + เก็บเงินเยอะ ใน Asphodel ผลักลงลาวาได้เปรียบสุด ๆ (ระวังผลักศัตรูออกจากพร AoE)' },
];

const DUOS = [
  { pair: 'Zeus × Poseidon', effect: 'สายฟ้า + คลื่นกระแทก: ตอนผลักศัตรูจะปล่อยสายฟ้าออกมาด้วย เคลียร์ฝูงโหด' },
  { pair: 'Zeus × Demeter', effect: 'Jolted เจอ Chill: สองสถานะส่งผลต่อกัน ทำดาเมจก้อนใหญ่' },
  { pair: 'Ares × Artemis', effect: 'Doom + คริ: คริใส่เป้าที่ติด Doom ดาเมจพุ่งกระฉูด' },
  { pair: 'Aphrodite × Ares', effect: 'Weak + Doom: ศัตรูตีเราเบาลง แถมค่อย ๆ ระเบิดตายเอง' },
  { pair: 'Artemis × Aphrodite', effect: 'คริการันตีใส่ศัตรูที่ติด Weak เบิร์สต์เป้าเดี่ยวโหด' },
  { pair: 'Athena × Zeus', effect: 'dash สะท้อนแล้วปล่อยสายฟ้ารอบตัว กันไปตีไปในจังหวะเดียว' },
  { pair: 'Demeter × Dionysus', effect: 'Chill + Hangover: ยืนกดดาเมจต่อเนื่องแบบคุมเกมเต็มจอ' },
  { pair: 'Poseidon × Ares', effect: 'ผลักศัตรูเข้าใบมีดหมุน (Blade Rift) แรงขึ้นเป็นเท่าตัว' },
];

const LEGENDARY = [
  { god: 'Zeus', name: 'Splitting Bolt', effect: 'เอฟเฟกต์สายฟ้าทุกครั้งจะปล่อยประกายเพิ่มอีกชุด ช่วยเสริมดาเมจและเคลียร์ฝูง', req: 'ต้องมี Storm Lightning, Double Strike หรือ High Voltage อย่างน้อย 1 ชิ้น' },
  { god: 'Ares', name: 'Vicious Cycle', effect: 'Blade Rift แรงขึ้นทุกครั้งที่โดนศัตรูต่อเนื่อง เหมาะกับบิลด์ใบมีดหมุน', req: 'ต้องมี Black Metal หรือ Engulfing Vortex' },
  { god: 'Athena', name: 'Divine Protection', effect: 'ได้เกราะกันดาเมจ 1 ครั้งที่ชาร์จคืนได้เรื่อย ๆ อึดขึ้นมหาศาล', req: 'ต้องมี boon Athena หลายชิ้น' },
  { god: 'Aphrodite', name: 'Unhealthy Fixation', effect: 'เอฟเฟกต์ Weak มีโอกาส 15% ทำให้ศัตรูติด Charm และหันไปโจมตีพวกเดียวกัน', req: 'ต้องมีพรแกนหลัก Aphrodite 1 ชิ้น และพรเสริม Weak อีก 1 ชิ้น' },
];

const BOON_KINDS = [
  { title: 'Duo Boon', color: '#ff9a5a', desc: 'รวมพลัง 2 เทพ ต้องมี boon เกี่ยวข้องจากทั้งสององค์ก่อน จึงจะมีให้เลือก' },
  { title: 'Chaos Boon', color: '#a888e8', desc: 'ผ่านประตู Chaos รับคำสาปสั้น ๆ แลกบัฟถาวรทั้งรัน มักแรงกว่าพรปกติ' },
  { title: 'Pom of Power', color: '#5fe0d1', desc: 'อัพเลเวล boon ที่มีอยู่ให้แรงขึ้น — ทุ่มลง boon หลักของบิลด์คุ้มสุด' },
];

const BIOMES = [
  { no: '01', name: 'Tartarus', latin: 'The Dungeon of the Dead', color: '#d16a4a', vibe: 'คุกใต้สุดของยมโลก โทนแดง-ส้ม ด่านแรกที่ปูพื้นฐาน ศัตรูไม่ซับซ้อน', enemies: 'วิญญาณทรมาน, นักธนู, ระเบิด', boss: 'Megaera', bossTip: 'หนึ่งในสามพี่น้อง Fury ระวังท่าแส้กวาดและโซนบนพื้น หลบให้ดีแล้วเข้าตี' },
  { no: '02', name: 'Asphodel', latin: 'The Fields of Fire', color: '#e0902e', vibe: 'ทุ่งลาวาเดือด มีสะพานคั่นบ่อลาวา การวางตำแหน่งสำคัญมาก', enemies: 'กะโหลกไฟ, ตัวระเบิด, ศัตรูโล่', boss: 'Bone Hydra', bossTip: 'ไฮดร้าหลายหัวที่งอกใหม่ได้ โฟกัสหัวหลักและหลบลำแสง/พ่นไฟให้ดี' },
  { no: '03', name: 'Elysium', latin: 'The Vale of Heroes', color: '#9bbf5a', vibe: 'สรวงสวรรค์ของวีรบุรุษ สวยแต่ศัตรูอึดและถือโล่ ต้องเล่นเป็น', enemies: 'วิญญาณวีรบุรุษ, ศัตรูโล่/หอก', boss: 'Theseus & Asterius', bossTip: 'สู้สองต่อหนึ่ง! Asterius (มิโนทอร์) พุ่งชนแรง ส่วน Theseus เรียก boon เทพ จัดการมิโนทอร์ก่อนมักง่ายกว่า' },
  { no: '04', name: 'Temple of Styx', latin: 'The Final Passage', color: '#4bb3a6', vibe: 'ด่านสุดท้าย เขาวงกตให้เลือกประตูหาทางออก เก็บของก่อนเจอบอสใหญ่', enemies: 'ซาเทียร์หนวด, ผู้พิทักษ์มินิบอส', boss: 'Hades', bossTip: 'พ่อของคุณเอง! มี 2 เฟส เก็บเลือด/ของให้พร้อมก่อนเข้า ชนะ = หนีสำเร็จ แล้วเนื้อเรื่องจะไปต่อ' },
];

const MAP_EXTRAS = [
  { name: "Charon's Shop", desc: 'โผล่ทุกโซน ใช้ทอง (Obols) ซื้อ boon/ของ/เลือด' },
  { name: 'Chaos Gate', desc: 'รับคำสาปสั้น ๆ แลกบัฟถาวรทั้งรัน' },
  { name: 'Infernal Gate', desc: 'ห้องท้าทายมีดาเมจกดดัน แลกรางวัลก้อนใหญ่' },
  { name: 'Well of Charon', desc: 'ซื้อตอนนี้ รับผลในโซนถัดไป' },
  { name: 'Fishing', desc: 'จุดตกปลา (ปลดผ่าน Contractor) แลกวัตถุดิบพิเศษ' },
];

const MIRROR = [
  { pair: 'Shadow ↔ Fiery Presence', desc: 'Attack/Special แรงขึ้นเมื่อโจมตีด้านหลัง ↔ แรงขึ้นเมื่อโจมตีศัตรูที่ยังไม่เสียพลัง' },
  { pair: 'Death ↔ Stubborn Defiance', desc: 'ฟื้นได้สูงสุด 3 ครั้งต่อรัน ↔ ฟื้น 1 ครั้งต่อห้องและชาร์จใหม่เมื่อเข้าห้องถัดไป' },
  { pair: 'Greater ↔ Ruthless Reflex', desc: 'เพิ่ม Dash อีก 1 ครั้ง ↔ หลบเกือบโดนแล้วได้ดาเมจและโอกาส Dodge ชั่วคราว' },
  { pair: 'Boiling ↔ Abyssal Blood', desc: 'Attack/Special แรงขึ้นกับศัตรูที่มี Cast ปัก ↔ ศัตรูที่มี Cast ปักเคลื่อนที่ช้าลงและทำดาเมจน้อยลง' },
  { pair: 'Chthonic Vitality', desc: 'ฟื้นเลือดเล็กน้อยทุกครั้งที่เข้าห้องใหม่ (อึดขึ้นเยอะสำหรับมือใหม่)' },
];

const UPGRADES = [
  { color: '#e7c26a', title: 'Weapon Aspects', html: 'อัพ Aspect ของอาวุธด้วย <b class="c-titan">Titan Blood</b> ที่แท่นวางอาวุธ แต่ละอันมี 5 ระดับ · Aspect ซ่อนปลดผ่านคำพยากรณ์ (Fated List) หลังเนื้อเรื่องถึงจุดหนึ่ง' },
  { color: '#e0453a', title: 'Pact of Punishment (Heat)', html: 'ปลดหลังหนีสำเร็จครั้งแรก เปิดเงื่อนไขเพิ่ม "Heat" เพื่อรางวัลที่ดีขึ้น (bounty) — ปรับความยากได้เองตามที่ไหว ไม่ต้องรีบ' },
  { color: '#6fd0e0', title: 'House Contractor', html: 'ใช้ <b style="color:#ff5a4d">Gems</b> / <b style="color:#6fd0e0">Diamonds</b> ปลดฟีเจอร์และตกแต่งบ้าน เช่น ตกปลา เพิ่มโอกาสเจอ Chaos/Well ห้องรางวัลพิเศษ' },
  { color: '#5fe0d1', title: 'Fated List (คำพยากรณ์)', html: 'เช็กลิสต์ภารกิจที่ให้รางวัลใหญ่ เช่น ชนะด้วยอาวุธครบทุกอัน ปลด Aspect ซ่อน ใช้เป็นเป้าหมายระยะยาวได้ดี' },
];

const KEEPSAKES = [
  { name: 'Old Spiked Collar', from: 'Cerberus', effect: '+HP สูงสุดตอนเริ่มรัน อึดขึ้นทันที เหมาะมือใหม่' },
  { name: 'Lucky Tooth', from: 'Skelly', effect: 'ฟื้นคืนชีพฟรี 1 ครั้งต่อรัน กันพลาด' },
  { name: 'Myrmidon Bracer', from: 'Achilles', effect: 'ลดดาเมจจากด้านหน้าอย่างมากช่วงต้น (เหมือนเกราะกันหน้า)' },
  { name: 'Pierced Butterfly', from: 'Thanatos', effect: 'สะสมดาเมจเพิ่มเมื่อเคลียร์ห้องโดยไม่โดนตี ยิ่งทำต่อเนื่องยิ่งแรง' },
  { name: 'Distant Memory', from: 'Orpheus', effect: 'ดาเมจเพิ่มกับศัตรูที่อยู่ไกล เหมาะสายธนู/ปืน' },
  { name: 'Bone Hourglass', from: 'Charon', effect: 'ไอเทมที่ซื้อจาก Well of Charon มีระยะเวลาเพิ่มขึ้นหลายห้อง' },
  { name: 'Chthonic Coin Purse', from: 'Hypnos', effect: 'เริ่มรันพร้อมทอง (Obols) ติดตัว ซื้อของได้เร็ว' },
  { name: 'Lambent Plume', from: 'Hermes', effect: 'สะสม dodge/ความเร็วเมื่อเคลียร์ห้องไว เหมาะสายว่องไว' },
  { name: 'God Keepsakes (all gods)', from: 'Olympian Gods', effect: 'การันตีให้เทพองค์นั้นเสนอ boon ก่อน + เรริตี้สูงขึ้น = บังคับบิลด์ได้' },
];
